### ISSUE TITLE
Add New Methods

### ISSUE THREAD

**Issue by JonHerke-TG** [parkererickson/pyTigerGraph#10]
### Request:
Add new methods to interact with TigerGraph's built-in REST endpoints. Full list of built-in Methods [https://docs.tigergraph.com/dev/restpp-api/built-in-endpoints](https://docs.tigergraph.com/dev/restpp-api/built-in-endpoints)

**Examples:** 
GetNode/GetNodeSet, 
PutNode/PutNodeSet, 
DeleteNode/DeleteNodeSet
GetEdge/GetEgeSet, 
PutEdge/PutEdgeSet, 
DeleteEdge/DeleteEdgeSet
GetNeighborSet,
PutNeighborSet,

**Comment by JonHerke-TG** [comment]
@parkererickson Can you assign this to me?

**Comment by parkererickson** [comment]
This is a good one as well!

**Comment by parkererickson** [comment]
GetNode and GetEdge should be done now - have to test

**Comment by parkererickson** [comment]
Updated with version 0.0.5.1
