### ISSUE TITLE
Issue with using pip install pyTigerGraph

### ISSUE THREAD

**Issue by JonHerke-TG** [parkererickson/pyTigerGraph#2]
I'm experimenting with Google colaboratory (Colaboratory is a free Jupyter notebook environment that requires no setup and runs entirely in the cloud) with the pyTigerGraph tool. https://pypi.org/project/pyTigerGraph/

I'm getting en error when running:

Command:

`!pip install pyTigerGraph`

Error:

`Collecting pyTigerGraph Using cached https://files.pythonhosted.org/packages/0b/0c/5574eebf4e351659c7d7154e781cb49b166d6248b09bea5be38deb86ea6b/pyTigerGraph-0.0.2.tar.gz ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.`

**Comment by parkererickson** [comment]
Fixed
