### ISSUE TITLE
Error installing on Raspberry Pi4

### ISSUE THREAD

**Issue by fjblau** [parkererickson/pyTigerGraph#32]
The pip installation seems to be calling an install for the json libraries that are built in to Python3, and it is throwing this error on install:

pi@raspberrypi:~/py532lib $ pip3 install pyTigerGraph
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting pyTigerGraph
  Downloading https://www.piwheels.org/simple/pytigergraph/pyTigerGraph-0.1-py3-none-any.whl
Collecting json (from pyTigerGraph)
Could not install packages due to an EnvironmentError: 404 Client Error: Not Found for url: https://pypi.org/simple/json/

**Comment by parkererickson** [comment]
@fjblau strange... that wheel is not up to the current version. We are at v0.0.9.6.2. Also, we have moved all further development to https://github.com/pyTigerGraph/pyTigerGraph (other people will see this issue if you open there).
