### ISSUE TITLE
Output results to DGL and/or networkx graph

### ISSUE THREAD

**Issue by parkererickson** [parkererickson/pyTigerGraph#5]

**Comment by dmccreary** [comment]
Parker,

Thank you for working on this software!  I have been using a graph layout system call GraphViz for a long time.  It is very powerful, has tones of options,  but a bit tricky to get set up in Jupyter Notebooks.

For an example of how to display the directory structure of the DonkeyCar here is an example:

https://github.com/dmccreary/arl/blob/e5f8fd0b3f92dc1395edc87bbcc48c4c18fba669/DonkeyCar-Directories.ipynb

**Comment by parkererickson** [comment]
That looks really good! Looking further into this, I'm not sure if we can include this (or networkx or dgl graphs) in the pyTigerGraph library, just because everybody's schema (and queries to get the data) look different. If there was a standard way to pull things out of the graph then it would be possible, but I don't know yet. Maybe @jonherke has a solution for that?
