### ISSUE TITLE
Store Credentials Separately

### ISSUE THREAD

**Issue by JonHerke-TG** [parkererickson/pyTigerGraph#9]
### Proposed Solution
**credlib.py** -- universal library to handle credentials

```
class credential:
    def __init__(self, hostname, username, password):
        self.hostname = hostname
        self.username = username
        self.password = password
```

**mycredentials.py** -- my local file to store all credentials from credlib import credential
```
sys_prod = credential("srv01", "user", "pass")
sys_stg = credential("srv02", "user", "pass")
sys_db = credential("db01", "userdb", "passdb")
```

**mysystemlib.py** -- this is a general library to access my system (both new credential system and legacy is supported)

```
from credlib import credential

def system_login(*args): # this is new function definition
#def system_login(hostname, username, password): # this was previous function definition

    if len(args) == 1 and isinstance(args[0], credential):
        hostname = args[0].hostname
        username = args[0].username
        password = args[0].password
    elif len(args) == 3:
        hostname = args[0]
        username = args[1]
        password = args[2]
    else:
        raise ValueError('Invalid arguments')

    do_login(hostname, username, password) # this is original system login call
```
**main.py** -- main script that combines credentials and system libs

```
from mycredentials import sys_stg, sys_db
import mysystemlib
...
mysystemlib.system_login(sys_stg)
```
Please note that the legacy hostname/username/password way still works so it does not affect old scripts:

`mysystemlib.system_login("srv02", "user", "pass")`

**This has a lot benefits:**
- same credential system across all our python scripts
- files with passwords are separated (files can have more strict permissions)
- files are not stored in our git repositories (excluded via .gitignore) so that our python scripts/libs can be shared with others without exposing credentials (everyone defines their own credentials in their local files)
- if a password needs to be changed, we do it at a single place only

Proposed solution origin --> https://stackoverflow.com/questions/25501403/storing-the-secrets-passwords-in-a-separate-file

**Comment by parkererickson** [comment]
This makes a lot of sense - will look at it later

**Comment by JonHerke-TG** [comment]
I put this here primarily to remind me to put it in.. I need to start adding features.

**Comment by parkererickson** [comment]
Sounds good

**Comment by parkererickson** [comment]
Closing this, I think the solution outlined [here](https://parkererickson.github.io/pyTigerGraph/Auth/) works pretty well.
